name: SaiGE
version: '${version}'
main: dev.arctic.saige.SaiGE
api-version: '1.20'
libraries:
  - com.theokanning.openai-gpt3-java:service:0.18.2
load: STARTUP
commands:
  ai:
    description: Control the AI behavior.
    usage: "/ai <subcommand>"
